# Generated by Django 4.2.30 on 2026-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer_admin', 'Customer Admin'), ('customer_user', 'Customer User'), ('project_manager', 'Project Manager')], default='customer_user', max_length=20),
        ),
    ]
