# Generated by Django 4.2.30 on 2026-05-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
        ('accounts', '0002_guest_role_and_permissions'),
    ]

    operations = [
    ]
