# Generated by Django 4.2.30 on 2026-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260513_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer_admin', 'Customer Admin'), ('customer_user', 'Customer User'), ('project_manager', 'Project Manager'), ('guest', 'Guest')], default='customer_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
