# Generated by Django 4.2.30 on 2026-05-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role_alter_guestpermission_id'),
    ]

    operations = [
    ]
