# Generated by Django 4.2.30 on 2026-04-24 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('milestone_updated', 'Milestone Updated'), ('milestone_completed', 'Milestone Completed'), ('milestone_delayed', 'Milestone Delayed'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_commented', 'Ticket Commented'), ('project_updated', 'Project Updated'), ('sign_off_requested', 'Sign Off Requested'), ('sign_off_done', 'Sign Off Done')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('milestone_id', models.PositiveIntegerField(blank=True, null=True)),
                ('document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('uploaded', 'Uploaded'), ('resolved', 'Resolved'), ('signed', 'Signed Off'), ('commented', 'Commented'), ('assigned', 'Assigned')], max_length=20)),
                ('entity_type', models.CharField(help_text='e.g. Ticket, Milestone, Document', max_length=50)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
